---
<% @vagrant = system('which vagrant 2>&1 >/dev/null') %>
driver:
  name: docker
  hostname: kitchen-salt.ci.local
  use_sudo: false
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>
  provision_command:
    - DEBIAN_FRONTEND=noninteractive apt-get install -y python-pip python-dev gcc git locales console-data
provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X -p git -p curl -p sudo
  formula: tests
  require_chef: false
  init_environment: |
    sudo mkdir -p /tmp/kitchen/var/cache/salt/master
  salt_copy_filter:
    - .filter_hidden
  vendor_repo:
    - type: apt
      url: http://apt.mirantis.com/trusty
      key_url: http://apt.mirantis.com/public.gpg
      components: salt
      distribution: nightly
    - type: ppa
      name: neovim-ppa/unstable
    - type: spm
      url: https://spm.hubblestack.io/2016.7.1
      name: hubblestack
  dependencies:
    - name: foo
      path: ./tests/formula-foo
    - name: nginx
      repo: apt
      package: salt-formula-nginx
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux.git
    - name: git
      repo: git
      source: https://github.com/salt-formulas/salt-formula-git.git
    - name: postfix
      repo: git
      source: https://github.com/salt-formulas/salt-formula-postfix
    - name: hubblestack_nova
      repo: spm
      package: https://spm.hubblestack.io/nova/hubblestack_nova-2016.10.1-1.spm
  state_top:
    base:
      "*":
        - tests.sudo
        - git
  pillars:
    top.sls:
      base:
        "*":
          - git
    git.sls:
      git:
        client:
          enabled: true
          user:
          - user:
              name: jdoe
              email: j@doe.com
      linux:
        system:
          enabled: true
          user:
            jdoe:
              enabled: true
              sudo: true
              full_name: John Doe
              home: /home/jdoe
  grains:
    noservices: True

platforms:
  - name: ubuntu-14.04
    provisioner:
      salt_apt_repo: 'https://repo.saltstack.com/apt/ubuntu/14.04/amd64/'
      salt_apt_repo_key: 'https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub'
      init_environment: |
        sudo mkdir -p /tmp/kitchen/var/cache/salt/master
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y software-properties-common
      salt_bootstrap_options: -X -p git -p curl -p sudo -p software-properties-common
  - name: ubuntu-16.04
    provisioner:
      init_environment: |
        sudo mkdir -p /tmp/kitchen/var/cache/salt/master
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y software-properties-common
      salt_bootstrap_options: -X -p git -p curl -p sudo -p software-properties-common
  - name: debian-8
    provisioner:
      salt_apt_repo: 'https://repo.saltstack.com/apt/debian/8/amd64'
      salt_apt_repo_key: 'https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub'
  - name: debian-9
    provisioner:
      salt_apt_repo: 'https://repo.saltstack.com/apt/debian/9/amd64'
      salt_apt_repo_key: 'https://repo.saltstack.com/apt/debian/9/amd64/latest/SALTSTACK-GPG-KEY.pub'
  - name: centos-7
    driver_config:
      provision_command:
        - yum install -y epel-release
        - yum install -y python-pip python-devel gcc git gcc-c++
    provisioner:
      salt_yum_repo: 'https://repo.saltstack.com/yum/redhat/$releasever/$basearch/%s'
      salt_yum_rpm_key: 'https://repo.saltstack.com/yum/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub'
  - name: centos-6
    provisioner:
      salt_yum_repo: 'https://repo.saltstack.com/yum/redhat/$releasever/$basearch/%s'
      salt_yum_rpm_key: 'https://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub'
      pip_bin: pip2.7
    driver_config:
      provision_command:
        - yum install -y epel-release https://centos6.iuscommunity.org/ius-release.rpm
        - yum install -y python27-pip python27-devel gcc git gcc-c++
<% if @vagrant != false %>
  - name: windows-2012r2
    driver:
      box: opentable/win-2012r2-datacenter-amd64-nocm
      communicator: winrm
      name: vagrant
      gui: true
    provisioner:
      init_environment: |
        Clear-Host
        $AddedLocation ="c:\salt"
        $Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"
        $OldPath = (Get-ItemProperty -Path "$Reg" -Name PATH).Path
        $NewPath= $OldPath + ’;’ + $AddedLocation
        Set-ItemProperty -Path "$Reg" -Name PATH –Value $NewPath
      salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1
      salt_bootstrap_options: ''
      state_top:
        base:
          "*":
            - foo
      dependencies:
        - name: foo
          path: ./tests/formula-foo
        - name: hubblestack_nova
          repo: spm
          package: https://spm.hubblestack.io/nova/hubblestack_nova-2016.10.1-1.spm
  - name: freebsd-11
    driver:
      box: bento/freebsd-11.0
      name: vagrant
    provisioner:
      salt_bootstrap_options: -X -p git -p curl -p sudo -p bash -p py27-sqlite3
      state_top:
        base:
          "*":
            - tests.sudo
      dependencies:
        - name: foo
          path: ./tests/formula-foo
        - name: postfix
          repo: git
          source: https://github.com/salt-formulas/salt-formula-postfix
        - name: hubblestack_nova
          repo: spm
          package: https://spm.hubblestack.io/nova/hubblestack_nova-2016.10.1-1.spm
<% end %>
suites:
  - name: apt
    provisioner:
      salt_install: apt
    includes:
      - debian-8
      - debian-9
      - ubuntu-14.04
      - ubuntu-16.04
  - name: yum
    provisioner:
      salt_install: yum
      init_environment: |
        sudo mkdir -p /tmp/kitchen/var/cache/salt/master
        sudo yum install -y git
    includes:
      - centos-6
      - centos-7
  - name: bootstrap
<% if @vagrant != false %>
    excludes:
      - freebsd-11
      - windows-2012r2
<% end %>
  - name: pip
    provisioner:
      salt_install: pip
<% if @vagrant != false %>
    excludes:
      - freebsd-11
      - windows-2012r2
  - name: vagrant
    includes:
      - freebsd-11
      - windows-2012r2
<% end %>
verifier:
  name: shell
  remote_exec: false
  command: pytest -v tests/integration/
